# Generated by Django 2.1.15 on 2022-03-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animalloss',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('animal_killed', models.IntegerField(blank=True, null=True)),
                ('habitat_loss', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animalloss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'disaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disastergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('disaster_group', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'disastergroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disastertype',
            fields=[
                ('type', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'disastertype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Humanloss',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('male_death', models.IntegerField(blank=True, null=True)),
                ('female_death', models.IntegerField(blank=True, null=True)),
                ('injured', models.IntegerField(blank=True, null=True)),
                ('affected_family', models.IntegerField(blank=True, null=True)),
                ('dispalced_male', models.IntegerField(blank=True, null=True)),
                ('dispalced_female', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'humanloss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tole', models.CharField(blank=True, db_column='Tole', max_length=40, null=True)),
                ('municipiality', models.CharField(blank=True, db_column='Municipiality', max_length=40, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propertyloss',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fully_damaged_building', models.IntegerField(blank=True, null=True)),
                ('partially_damaged_building', models.IntegerField(blank=True, null=True)),
                ('estimated_loss', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'propertyloss',
                'managed': False,
            },
        ),
    ]
